### ISSUE TITLE
mdpopups dependency

### ISSUE THREAD

**Issue by buildersbrewery** [Makopo/sublime-text-tooltip-lsl#3]
Why remove the mdpopups dependency from the Makopo/sublime-text-lsl#38? The good thing about it was, that tooltips:
- would inherit the style from the currently used color scheme.
- take markdown syntax for the tooltip text.

---

Add `./dependencies.json` with:

``` json
{
    "*": {
        ">=3080": [
            "pygments",
            "python-markdown",
            "mdpopups",
            "python-jinja2",
            "markupsafe"
        ]
    }
}
```

In python script add:

``` python
if 3080 <= int(sublime.version()):
    import mdpopups
```

**Comment by Makopo** [comment]
It will introduce third-party dependencies, so I have to consider well before deciding to implement.
So let me treat it as future enhance request. If others want to implement it, please add any reaction or comment to this issue. Thanks.

**Comment by buildersbrewery** [comment]
Changes in **Build 3116** probably make this dependency less useful, however mdpopups still gives the advantage of being able to use Markdown. See #5 for a PR showing the usage of the new APIs.
